name: Aggiorna Selezione Vini

on:
  schedule:
    - cron: '0 6 * * *' # Gira ogni giorno alle 06:00 UTC
  workflow_dispatch: # Permette anche l'avvio manuale

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configura Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installa dipendenze
        run: pip install beautifulsoup4

      - name: Esegui Scraper
        run: python scraper.py

      - name: Salva modifiche
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.html
          git commit -m "Aggiornamento automatico offerte vini" || exit 0
          git push
